version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
