# Generated by Django 4.1.2 on 2023-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
    ]
