# Generated by Django 4.1.2 on 2023-11-14 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_treasurehunt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Score cannot exceed 5.'), django.core.validators.MinValueValidator(1, message='Score cannot be less than 1.')]),
        ),
    ]
