# Generated by Django 4.1.2 on 2023-12-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_clue_picture_alter_treasurehunt_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehunt',
            name='end_location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='treasurehunt',
            name='start_location',
            field=models.CharField(max_length=40),
        ),
    ]
