# Generated by Django 4.1.2 on 2023-12-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_treasurehunt_end_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='description',
        ),
        migrations.AddField(
            model_name='clue',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
