# Generated by Django 4.1.2 on 2023-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_clue_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='canceled',
            new_name='is_canceled',
        ),
        migrations.AddField(
            model_name='game',
            name='current_clue_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
