# Generated by Django 4.1.2 on 2023-12-14 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_canceled_game_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
