# Generated by Django 4.1.2 on 2024-01-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedHints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hint')),
            ],
        ),
    ]
